# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64eb644501362f116547acaef312a9418ab587a3d41bb0e14215e77b67aa7c15afa50a4d773d1b142a94e4f1ec879c306974915bf5f227235a06b5ab6eb38762

test:
  secret_key_base: 68e486e07a3e607ff956d1880cab3c90d53887e16cfd5741aee78b5185097b4584b2f38fda5c0e9ead16f8867a309c63e75ff36bf48d6bd67245bd5c3ba5d8a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
